### ISSUE TITLE
ERROR - toggl2clockify - json entry 'TogglKey' must be a strings

### ISSUE THREAD

**Issue by WvdW** [pieye/toggl2clockify#10]
Hi,

Platform: Ubuntu 18.04 using python 2.7.15.

I was trying to run the app for a test migration and keep on getting the following error:
ERROR - toggl2clockify - json entry 'TogglKey' must be a strings

I have double-checked the format used for the API key in the config.json file and its complying 100% for the format indicated in your installation and preparation documentation. I have also done a Google search to check if someone else has maybe experienced the same problem but could not find any other related article.

Is this an app error or a config file error? The API key used was copied and pasted directly from the Toggl UI so I know it is correct.

**Comment by Coimbra1984** [comment]
The problem is probably python 2.7. Can you use python 3?

**Comment by WvdW** [comment]
I updated to python 3.6.7-1 and ran it again. Its now going past the initial key error but as soon as it gets to phase 3 (import projects) then it fails with the error:
WARNING - Clue - error adding user XXX to clockify project, msg=User XXX not found in workspace XXX

The user does exist with the exact same email address, has been marked as admin on both sides, I ensured that the profile name is exactly the same on both sides, as well as the workspace name (including capitalisation). The workspace name has ' in the name. Could that perhaps be throwing it?

It runs through the whole phase 3 but shows the same error line for every project it tries to add the user to. In the end it completes phase 3 but all records failed and nothing gets added to Clockify.

Phase 4 (import time entries) starts but it fails with the following error for each of the imported time entries for user 1:
WARNING - ClockifyAPI - user XXX not found
When it starts with user 2's time entries then the .py script starts failing in several of its lines with errors.

I have run the script several times and every time it got a little further than the previous time but it doesn't want to proceed at all past the failures of phase 4.

**Comment by Coimbra1984** [comment]
Okay, let's try to solve the first WARNING first.
The tool first tries to resolve all clockify keys, can you check again that you get the output:
testing clockify APIKey XXXXX
...ok, key resolved to email XXXX@XXXX.COM
Also a file called clockify_users.json should be created in the same folder, can you also open that file and check the content.
The emails must also match exactly (lower/UPPER case).
The ' in the workspace name should not be a problem.
Most helpful should be the content of clockify_users.json This file contains all the users found in the given workspace, you must see the corresponding user in that file.

**Comment by WvdW** [comment]
Yes, good call. That seems to have resolved it. On the Toggl side the primary email address started with an uppercase and on the Clockify side it had a lower case. Thanks :)

Some observations that might be worth noting in your "preparing the environment" instructions:
- Open Toggl and Clockify side-by-side and compare the Workspace and Profile settings to ensure they both match up exactly prior to running the script
- The Workspace owner's email address must be the exact same on both sides (including capitalization)
- Rename the Workspace name on both sides to something simple without any apostrophes or special characters
- The script is very sensitive to a stable network connection and sufficient bandwidth speed otherwise it times out
- Run a test migration just with the Workspace owner's API key on the Clockify side first. If that completes successfully but with warnings for the other missing users then you can run the migration a second time with all of the others users' Clockify API keys also included in the config.json file.
- Don't be afraid to run the script several times as you make changes to the config.json file. It will just skip over existing content and fill in whatever blanks there may be.

Thanks for your effort in writing this script! It has saved many hours of having to manually migrate content.

**Comment by scottrobertson** [comment]
Getting this too. When i try and run with `python3` i get:

```
Traceback (most recent call last):
  File "toggl2clockify.py", line 13, in <module>
    import dateutil
ModuleNotFoundError: No module named 'dateutil'
```

**Comment by Coimbra1984** [comment]
Okay, this is really strange, because 'dateutil' is a standard python library.
You can try:
sudo apt-get install python3-dateutil
or check if you have pip3 and install it with pip:
pip3 install python-dateutil
