### ISSUE TITLE
Entries migrated on wrong project

### ISSUE THREAD

**Issue by dayaketu** [pieye/toggl2clockify#14]
Hello!

I have done the migration as per the instructions. After the migration, I have seen that some tasks are added on the wrong client and project. For example, I have one task "Calendario Social Media", on project "Social Media" on client "Cambia un Destino". and I have another exact same task and project, but on customer "PNA". So everything the same, except different client.

I have seen that almost all tasks on this combination from client "Cambia un Destino" were migrated as "PNA". This issue repeats itself not only on this specific instance of task-project-client, but on many others which task-project are the same but different client.

Let me know how I can help. Thanks so much.

**Comment by alex-ong** [comment]
I am working on a patch for this (I'm sure you have already migrated all your data)

**Comment by alex-ong** [comment]
Patched in #21.
Can be closed once #21 is merged.

**Comment by alex-ong** [comment]
This can be closed
