### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by Uniquark** [pieye/toggl2clockify#18]
Hi. Thank you for creating this tool. I would like to use it, but I'm running into an error. I know very little about Python, but I'm comfortable with the command line. I'm trying to run python3 toggl2clockify.py in Terminal on a MacBook Pro under Mojave (macOS 10.14). The error I'm getting is ModuleNotFoundError: No module named 'dateutil' immediately after invoking the command.

Digging a little deeper, it appears that toggl2clockify expects dateutil to be installed on my system. Where should I look to install that module?

Thanks

**Comment by alex-ong** [comment]
Hi,

This is super late, but you'll need to use pip (python package manager) to install a few things
`pip3 install pytz`
`pip3 install requests`
`pip3 install python-dateutil`

**Comment by Uniquark** [comment]
Hi alex-ong. Thanks for the reply. This is long enough ago that I no longer need the tool. I don't recall, but I think I found another tool that did the job, at least partially.
