### ISSUE TITLE
Duplicate check

### ISSUE THREAD

**Issue by acseven** [pieye/toggl2clockify#6]
Suggestion: A duplicate check for time entries and projects already in Clockify would be a very welcome addition, maybe even as a separate tool. After the many times I’ve done the process, I think some time entries got duplicated but I can’t say for sure. 

Regards

**Comment by Coimbra1984** [comment]
What do you exactly mean? A tool that checks for duplicated projects/time entries within the clockify workspace (i.e. without looking into toggl)?

**Comment by acseven** [comment]
Exactly that. I think it happened in between the attempts to sync everything.

**Comment by inyerade** [comment]
I have the same problem. I have more than 5 time time entry repetitions in some cases. I run many times the script because fail and I do not why, until I realize that I had to have all projects public in toggl.

**Comment by alex-ong** [comment]
>  I had to have all projects public in toggl.

I have added a patch for this in #21, it is now documented.

> A tool that checks for duplicated projects/time entries within the clockify workspace (i.e. without looking into toggl)?

This already works AFAIK.

This issue can be closed after merging #21

**Comment by alex-ong** [comment]
It already works (though buggily due to timezones bug) for time entries. Projects 100% works, if a project exists in clockify it is skipped.
