### ISSUE TITLE
Problem with Time records

### ISSUE THREAD

**Issue by vasblaz** [pieye/toggl2clockify#8]
Hi, I do have a problem with importing Time records from toggl to Clockify. I got imported all clients and projects but when it comes to Time records import, nothing really happen - see picture attached. Can you please help me with that? Thank you sooooo much :-)
![log_PrtScr](https://user-images.githubusercontent.com/51776430/59779043-d7e09180-92b7-11e9-95ca-dbbbb8fd5f51.PNG)

**Comment by Coimbra1984** [comment]
Hi,
I need a bit more information. It is difficult to help with this screenshot. Can you attach the log.txt file, but please remove any sensitive data before.

**Comment by vasblaz** [comment]
Hi, thanks a lot for your reply. Sending log attached :)
[log.txt](https://github.com/pieye/toggl2clockify/files/3309978/log.txt)

**Comment by Coimbra1984** [comment]
Okay, this is really strange...
I commited a more verbose output version. Can you update your local working copy and run the script again and most what it shows now for 

Phase 4 of 5: ...

Are you running the .exe version or the python version of the script?

**Comment by vasblaz** [comment]
I am running the .exe version. I download it again and run the script and there is no Phase 4 of 5: even shown anymore ... check log. file. Thank you for your time!!
(or do I have to try it with python?)
[log.txt](https://github.com/pieye/toggl2clockify/files/3310053/log.txt)

**Comment by Coimbra1984** [comment]
strange... Do you get any error output on the command line?

**Comment by vasblaz** [comment]
Well nothing at all ... no errors :-/

**Comment by Coimbra1984** [comment]
Okay, how do you exactly start the exe file? You should open a command prompt and run it inside the command prompt, than you should get at least the same output as in the log.txt file on the console.

**Comment by vasblaz** [comment]
I do have toggl2clockify.exe file and config.json file in the same folder and then I just open the .exe file and it runs automatically...once it is done, .exe file close itself and I have some outputs which is log.txt, toggl_projects_json and clockify_projects.json
Am I doing it wrong?

**Comment by Coimbra1984** [comment]
I guess it is better if you open a command prompt (select start button in windows and type "cmd") go to the exe folder and start it inside the command prompt this way if any error occurs, the output can still be seen on the command prompt and doesn't close automatically

**Comment by vasblaz** [comment]
OK...so I got this at the end:
![Výstřižek](https://user-images.githubusercontent.com/51776430/59846151-60fed380-935f-11e9-9269-d07c7a153bec.PNG)

**Comment by Coimbra1984** [comment]
uuups, sorry that was my mistake, can you update and run again...

**Comment by vasblaz** [comment]
So I did it and this is result...so it looks like it doesn´t run properly now (check PrtScr). Thank you a looot for your patience!!
![Výstřižek](https://user-images.githubusercontent.com/51776430/59848016-6ad70580-9364-11e9-8ab1-f0f06474bee4.PNG)

**Comment by Coimbra1984** [comment]
okay sorry, that was my mistake again :( can you try again, please...

**Comment by vasblaz** [comment]
No worries ... I am happy you are even willing to help me :) So I tried again ... and it awesomely perfectly work!! Thank you sooo much!! :)

**Comment by vasblaz** [comment]
It really made my day so thank you!! You are awesome :)

**Comment by Coimbra1984** [comment]
Cool, nice to hear!
